### ISSUE TITLE
To use or not to use clang-format

### ISSUE THREAD

**Issue by mpherg** [rodolfobandeira/iex-cpp-client#15]
@rodolfobandeira how to you feel about adding a clause to the README.md requiring clang-formatting for all contributions? It's a nice way to keep the formatting of the code consistently readable and maintainable. However, it also requires another tool. I like it because it can be easily integrated into nearly every editor, as well as git (`git clang-format`, anyone?).

**Comment by rodolfobandeira** [comment]
@mpherg Are you talking about that python script you've been using on your vim?

**Comment by mpherg** [comment]
Yes, for [Vim](https://clang.llvm.org/docs/ClangFormat.html#vim-integration). You can also integrate with [Emacs](https://clang.llvm.org/docs/ClangFormat.html#emacs-integration), [BBEdit](https://clang.llvm.org/docs/ClangFormat.html#bbedit-integration), [Visual Studio](
https://clang.llvm.org/docs/ClangFormat.html#visual-studio-integration), [Atom](https://atom.io/packages/clang-format), and probably several others.

**Comment by rodolfobandeira** [comment]
@mpherg I'm having some trouble to setup the `clang-format.py`. Basically looks like it requires python3. My vim doesn't accept python3 for some reason (installed via homebrew) so the `:pyf` command keeps invoking the clang-format using python 2.7 even though I have python 3.* installed on this machine. I also tried `:py3`, and even reinstalling vim with python3 support (which is not available using my current homebrew formula).

I'm gonna try again tonight but I'd love to use this format and have a consistent codebase.
For now, I vote to keep using as well! Thanks for bringing this in! It looks very useful!

**Comment by rodolfobandeira** [comment]
Got it working, the only issue I found so far is this. Which version of clang-format are you using? @mpherg 

```
YAML:35:27: error: unknown key 'SplitEmptyFunctionBody'
```

**Comment by mpherg** [comment]
Homebrew installs version 8, but I downgraded to version 5 for consistency with other platforms. This error is due to that key being removed in newer versions.

**Comment by rodolfobandeira** [comment]
Yeah, I just didn't get why it is showing this error if I'm running the latest version 8. But anyways, should be good now. Let's use clang-format from now on.
