### ISSUE TITLE
Implement getDividends

### ISSUE THREAD

**Issue by rodolfobandeira** [rodolfobandeira/iex-cpp-client#4]
Reference: https://iextrading.com/developer/docs/#dividends

**Comment by 42iscool42** [comment]
Are you interested in having this method return a struct similar to PriceData?

**Comment by rodolfobandeira** [comment]
Hi @42iscool42,

The [price endpoint](https://iextrading.com/developer/docs/#price) returns a single float like: `143.28` and requires just one parameter. A symbol like: `amzn`. 

The dividends endpoint will accept two input parameters instead of just one. `time_range` and `stock_symbol`. The returned data is also a bit different since it contains a list of fields, not just one unique value. It is up to you, the good thing about this repository is that it is pretty new, so there is a lot of space for improvement and creativity. I would create something like a list of structs like this: 


```
...
        "dividends.exDate": "2017-08-10",
        "dividends.paymentDate": "2017-08-17",
        "dividends.recordDate": "2017-08-14",
        "dividends.declaredDate": "2017-08-01",
        "dividends.amount": 0.63,
        "dividends.type": "Dividend income",
        "dividends.qualified": "Q"
...
```
